### PR TITLE
fix: make sure chrome for testing is installed and linked properly

### LINKED ISSUE #140: Non-standard Chrome for Testing installation
## Current behavior

On Linux, [circleci/browser-tools@2.1.0](https://github.com/CircleCI-Public/browser-tools-orb/releases/tag/v2.1.0) downloads Google [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) and unzips all files into the:

- `/usr/local/bin/chrome-linux64` directory

leaving also the original zip file in place:

- `/usr/local/bin/chrome-for-testing.zip`

Attempting to execute the following command fails:

```shell
chrome --version
```

Cypress does not detect the Chrome for Testing installation and fails to execute. See https://github.com/cypress-io/cypress/issues/31867.

## Expected behavior

The current version of `circleci/browser-tools` on Linux should follow the [Filesystem Hierarchy Standard (FHS)](https://refspecs.linuxfoundation.org/fhs.shtml) when installing [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/):

- `chrome-for-testing.zip` should be unzipped into `/opt`
- `/usr/local/bin` should contain a symbolic link to the `chrome` executable from Chrome for Testing located in a subdirectory of `/opt`
- After downloading `chrome-for-testing.zip`, it should be deleted
- The command `chrome --version` should successfully show the version of Chrome for Testing installed

## Steps to reproduce

https://github.com/MikeMcC399-CircleCI/cy-circleci-test-public/tree/cft

```yml
version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@2.1.0
jobs:
  test:
    docker:
      - image: cimg/node:22.16.0-browsers
    steps:
      - checkout
      - run:
          npm ci --frozen-lockfile
      - browser-tools/install_browser_tools:
          install_chrome_for_testing: true
          install_chrome: false
          install_chromedriver: false
          install_firefox: false
      - run:
          npx cypress info
      - run:
          DEBUG=cypress:launcher:*,cypress-verbose:launcher:* npx cypress info
      - run:
          name: show installation files
          command: |
            ls -al /usr/local/bin
            find /usr/local/bin/chrome-linux64
      - run:
          chrome --version || true
workflows:
  test-workflow:
    jobs:
      - test
```

## Logs

```text
DevTools listening on ws://127.0.0.1:39105/devtools/browser/fa194f06-2a7d-459b-a294-51d37a7c2e5f
Displaying Cypress info...

Detected no known browsers installed


Proxy Settings:
NO_PROXY: 127.0.0.1,localhost,circleci-internal-outer-build-agent

Learn More: https://on.cypress.io/proxy-configuration

Environment Variables: none detected

Application Data: /home/circleci/.config/cypress/cy/development
Browser Profiles: /home/circleci/.config/cypress/cy/development/browsers
Binary Caches: /home/circleci/.cache/Cypress

Cypress Version: 14.4.1 (stable)
System Platform: linux (Ubuntu - 22.04)
System Memory: 8.59 GB free 8.59 GB
```

```text
total 326768
drwxr-xr-x 1 circleci   1001        77 Jun 11 17:22 .
drwxr-xr-x 1 root     root          17 May 21 15:57 ..
-rw-r--r-- 1 root     root   173637372 Jun 11 17:22 chrome-for-testing.zip
drwxr-xr-x 8 root     root        4096 Jun 11 17:22 chrome-linux64
-rwxr-xr-x 1 root     root     2953216 Feb 29  2024 compose-switch
lrwxrwxrwx 1 circleci   1001        45 May 21 03:58 corepack -> ../lib/node_modules/corepack/dist/corepack.js
lrwxrwxrwx 1 root     root          32 Feb 29  2024 docker-compose -> /etc/alternatives/docker-compose
-rwxr-xr-x 1 root     root     9564805 Feb 29  2024 dockerize
-rwxr-xr-x 1     1000   1000   6132584 Feb 24 17:27 geckodriver
-rwxr-xr-x 1 circleci docker       405 Feb 25  2024 install-man-page.sh
-rwxr-xr-x 1 circleci   1001 121509208 May 21 03:57 node
lrwxrwxrwx 1 root     root          19 May 21 15:57 nodejs -> /usr/local/bin/node
lrwxrwxrwx 1 circleci   1001        38 May 21 03:58 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx 1 circleci   1001        38 May 21 03:58 npx -> ../lib/node_modules/npm/bin/npx-cli.js
lrwxrwxrwx 1 root     root          37 May 21 15:57 pnpm -> ../lib/node_modules/pnpm/bin/pnpm.cjs
lrwxrwxrwx 1 root     root          37 May 21 15:57 pnpx -> ../lib/node_modules/pnpm/bin/pnpx.cjs
-rw-r--r-- 1 root     root    10649948 May 21 15:58 selenium.jar
lrwxrwxrwx 1 root     root          27 May 21 15:57 yarn -> /opt/yarn-v1.22.22/bin/yarn
lrwxrwxrwx 1 root     root          30 May 21 15:57 yarnpkg -> /opt/yarn-v1.22.22/bin/yarnpkg
-rwxr-xr-x 1 circleci docker   9928856 Feb 25  2024 yq
-rw-r--r-- 1 circleci docker    206564 Feb 25  2024 yq.1
/usr/local/bin/chrome-linux64
/usr/local/bin/chrome-linux64/ABOUT
/usr/local/bin/chrome-linux64/MEIPreload
/usr/local/bin/chrome-linux64/MEIPreload/manifest.json
/usr/local/bin/chrome-linux64/MEIPreload/preloaded_data.pb
/usr/local/bin/chrome-linux64/PrivacySandboxAttestationsPreloaded
/usr/local/bin/chrome-linux64/PrivacySandboxAttestationsPreloaded/manifest.json
/usr/local/bin/chrome-linux64/PrivacySandboxAttestationsPreloaded/privacy-sandbox-attestations.dat
/usr/local/bin/chrome-linux64/WidevineCdm
/usr/local/bin/chrome-linux64/WidevineCdm/LICENSE
/usr/local/bin/chrome-linux64/WidevineCdm/_platform_specific
/usr/local/bin/chrome-linux64/WidevineCdm/_platform_specific/linux_x64
/usr/local/bin/chrome-linux64/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so
/usr/local/bin/chrome-linux64/WidevineCdm/manifest.json
/usr/local/bin/chrome-linux64/chrome
/usr/local/bin/chrome-linux64/chrome-wrapper
/usr/local/bin/chrome-linux64/chrome_100_percent.pak
/usr/local/bin/chrome-linux64/chrome_200_percent.pak
/usr/local/bin/chrome-linux64/chrome_crashpad_handler
/usr/local/bin/chrome-linux64/chrome_sandbox
/usr/local/bin/chrome-linux64/deb.deps
/usr/local/bin/chrome-linux64/icudtl.dat
/usr/local/bin/chrome-linux64/libEGL.so
/usr/local/bin/chrome-linux64/libGLESv2.so
/usr/local/bin/chrome-linux64/libvk_swiftshader.so
/usr/local/bin/chrome-linux64/libvulkan.so.1
/usr/local/bin/chrome-linux64/locales
/usr/local/bin/chrome-linux64/locales/af.pak
/usr/local/bin/chrome-linux64/locales/am.pak
/usr/local/bin/chrome-linux64/locales/ar.pak
/usr/local/bin/chrome-linux64/locales/bg.pak
/usr/local/bin/chrome-linux64/locales/bn.pak
/usr/local/bin/chrome-linux64/locales/ca.pak
/usr/local/bin/chrome-linux64/locales/cs.pak
/usr/local/bin/chrome-linux64/locales/da.pak
/usr/local/bin/chrome-linux64/locales/de.pak
/usr/local/bin/chrome-linux64/locales/el.pak
/usr/local/bin/chrome-linux64/locales/en-GB.pak
/usr/local/bin/chrome-linux64/locales/en-US.pak
/usr/local/bin/chrome-linux64/locales/es-419.pak
/usr/local/bin/chrome-linux64/locales/es.pak
/usr/local/bin/chrome-linux64/locales/et.pak
/usr/local/bin/chrome-linux64/locales/fa.pak
/usr/local/bin/chrome-linux64/locales/fi.pak
/usr/local/bin/chrome-linux64/locales/fil.pak
/usr/local/bin/chrome-linux64/locales/fr.pak
/usr/local/bin/chrome-linux64/locales/gu.pak
/usr/local/bin/chrome-linux64/locales/he.pak
/usr/local/bin/chrome-linux64/locales/hi.pak
/usr/local/bin/chrome-linux64/locales/hr.pak
/usr/local/bin/chrome-linux64/locales/hu.pak
/usr/local/bin/chrome-linux64/locales/id.pak
/usr/local/bin/chrome-linux64/locales/it.pak
/usr/local/bin/chrome-linux64/locales/ja.pak
/usr/local/bin/chrome-linux64/locales/kn.pak
/usr/local/bin/chrome-linux64/locales/ko.pak
/usr/local/bin/chrome-linux64/locales/lt.pak
/usr/local/bin/chrome-linux64/locales/lv.pak
/usr/local/bin/chrome-linux64/locales/ml.pak
/usr/local/bin/chrome-linux64/locales/mr.pak
/usr/local/bin/chrome-linux64/locales/ms.pak
/usr/local/bin/chrome-linux64/locales/nb.pak
/usr/local/bin/chrome-linux64/locales/nl.pak
/usr/local/bin/chrome-linux64/locales/pl.pak
/usr/local/bin/chrome-linux64/locales/pt-BR.pak
/usr/local/bin/chrome-linux64/locales/pt-PT.pak
/usr/local/bin/chrome-linux64/locales/ro.pak
/usr/local/bin/chrome-linux64/locales/ru.pak
/usr/local/bin/chrome-linux64/locales/sk.pak
/usr/local/bin/chrome-linux64/locales/sl.pak
/usr/local/bin/chrome-linux64/locales/sr.pak
/usr/local/bin/chrome-linux64/locales/sv.pak
/usr/local/bin/chrome-linux64/locales/sw.pak
/usr/local/bin/chrome-linux64/locales/ta.pak
/usr/local/bin/chrome-linux64/locales/te.pak
/usr/local/bin/chrome-linux64/locales/th.pak
/usr/local/bin/chrome-linux64/locales/tr.pak
/usr/local/bin/chrome-linux64/locales/uk.pak
/usr/local/bin/chrome-linux64/locales/ur.pak
/usr/local/bin/chrome-linux64/locales/vi.pak
/usr/local/bin/chrome-linux64/locales/zh-CN.pak
/usr/local/bin/chrome-linux64/locales/zh-TW.pak
/usr/local/bin/chrome-linux64/product_logo_48.png
/usr/local/bin/chrome-linux64/resources.pak
/usr/local/bin/chrome-linux64/rpm.deps
/usr/local/bin/chrome-linux64/v8_context_snapshot.bin
/usr/local/bin/chrome-linux64/vk_swiftshader_icd.json
/usr/local/bin/chrome-linux64/xdg-mime
/usr/local/bin/chrome-linux64/xdg-settings
/usr/local/bin/chrome-linux64/resources
/usr/local/bin/chrome-linux64/resources/accessibility
/usr/local/bin/chrome-linux64/resources/accessibility/reading_mode_gdocs_helper_manifest.json
/usr/local/bin/chrome-linux64/resources/accessibility/reading_mode_gdocs_helper
/usr/local/bin/chrome-linux64/resources/accessibility/reading_mode_gdocs_helper/content.js
/usr/local/bin/chrome-linux64/resources/accessibility/reading_mode_gdocs_helper/gdocs_script.js
/usr/local/bin/chrome-linux64/resources/inspector_overlay
/usr/local/bin/chrome-linux64/resources/inspector_overlay/main.js
/usr/local/bin/chrome-linux64/resources/inspector_overlay/inspector_overlay_resources.grd
/usr/local/bin/chrome-linux64/hyphen-data
/usr/local/bin/chrome-linux64/hyphen-data/hyph-de-1996.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-cu.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-nn.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-be.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-ka.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-kn.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-ml.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-te.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-cs.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-sl.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-or.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-da.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-lt.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-el.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-et.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-fr.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-mr.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-bn.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-ru.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-as.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-hr.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-pa.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-cy.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-es.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-und-ethi.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-ga.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-tk.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-gu.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-eu.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-bg.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-uk.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-it.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-nb.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-mul-ethi.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-nl.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-sv.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-af.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-en-gb.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-mn-cyrl.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-hu.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-sk.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-sq.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-hy.hyb
/usr/local/bin/chrome-linux64/hyphen-data/manifest.json
/usr/local/bin/chrome-linux64/hyphen-data/hyph-ta.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-la.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-pt.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-de-ch-1901.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-en-us.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-hi.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-lv.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-de-1901.hyb
/usr/local/bin/chrome-linux64/hyphen-data/hyph-gl.hyb
```

cc: @jennifer-shehane @AtofStryker

### PR DESCRIPTION
**Pull request by AtofStryker**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

Closes #140

### Description

Looks like there is an issue where Chrome for Testing is not linked properly after install. This PR moves the unzipped package to the `/opt` directory for linux and mac and symlinks the binary to `/usr/local/bin/chrome`

I also removed the `$SUDO apt-get satisfy -y --no-install-recommends "${pkg}";` as it tends to hang when there are no updates available. I could not get this part of the script to run

### CODE REVIEW

**Comment by marboledacci** [comment]
@AtofStryker  I'm not so confident about removing the `apt-get satisfy`. What kind of problems is it causing you?

**Comment by AtofStryker** [comment]
> @AtofStryker I'm not so confident about removing the `apt-get satisfy`. What kind of problems is it causing you?

It is indefinitely hanging the script. Are you able to get it to run?

File: src/scripts/install_chrome_for_testing.sh [hunk 1]
```diff
@@ -45,14 +49,13 @@ elif command -v apt >/dev/null 2>&1; then
...
+        $SUDO mv ./chrome-linux64 /opt/chrome-for-testing
+        $SUDO ln -fs /opt/chrome-for-testing/chrome /usr/local/bin/chrome
     else
         echo "Version $target_version doesn't exist"
         exit 1
     fi
-    $SUDO apt-get update
-    while read -r pkg; do
-        $SUDO apt-get satisfy -y --no-install-recommends "${pkg}";
-    done < chrome-linux64/deb.deps;
```
Comment (MikeMcC399) [inline src/scripts/install_chrome_for_testing.sh:55]: At this point in the script, `dep.deps`  has been moved to `/opt/chrome-for-testing/dep.deps`

If these script lines of code are restored, then that would need to be changed.

I don't know otherwise why this section, which was previous working, would no longer work.
Almost all the dependencies are already installed. 

In my repro steps, using the published version, I saw it installing only:

```text
The following NEW packages will be installed:
  libvulkan1
0 upgraded, 1 newly installed, 0 to remove and 137 not upgraded.
Need to get 128 kB of archives.
After this operation, 506 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvulkan1 amd64 1.3.204.1-2 [128 kB]
Fetched 128 kB in 0s (311 kB/s)     
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libvulkan1:amd64.
(Reading database ... 45380 files and directories currently installed.)
Preparing to unpack .../libvulkan1_1.3.204.1-2_amd64.deb ...
Unpacking libvulkan1:amd64 (1.3.204.1-2) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
```

Comment (marboledacci) [reply src/scripts/install_chrome_for_testing.sh:55]: That sounds right, just point to that file in the installation. We cannot just remove the dependencies installation. These are coming from the official installation guide from chrome-for-testing, and we cannot guarantee all environments will have them.

Comment (AtofStryker) [reply src/scripts/install_chrome_for_testing.sh:55]: I'll move the dependencies over to the new path, though it was previously hanging for me because I had `libvulkan1` installed, so there is nothing to read from in stdout, if that makes sense.
